pub mod checksum;
pub mod error;
pub mod fetch;
pub mod filter;
pub mod fs;
pub mod install;
pub mod lock;
pub mod manager;
pub mod manifest;
pub mod package;
pub mod types;
pub mod verify;

pub use error::RawdistError;
pub use fetch::{HttpClient, UreqClient, fetch_package};
pub use fs::{FileSystem, RealFs};
pub use install::{install_package, remove_package};
pub use lock::LockFile;
pub use manager::PackageManager;
pub use manifest::{load_manifest, save_manifest};
pub use package::{create_package, extract_to_temp, move_extracted};
pub use types::{Manifest, RawdistConfig};
pub use verify::verify_package;
